### ISSUE TITLE
Rename ArrayBasic and Array to Array and Sorting

### ISSUE THREAD

**Issue by JMCanning78** [IlanaRadinsky/datastructures-applets#2]
Please change the name of these Python modules as follows:

-  `ArrayBasic.py` to `Array.py` 
-  `Array.py` to `Sorting.py`

Please ensure the title bar for each window shows "Array" and "Sorting"

**Comment by JMCanning78** [comment]
In the Array.py module:

- Rename the "Delete" button in the GUI to "Delete Rightmost"
- Reorganize the text entry array and buttons that require an input value in the text entry array to be grouped together.  The "Delete Rightmost" button will be grouped separately to indicate it doesn't use the input value
- Add a new "Delete" button that:
  1.  Requires a input value
  2. Searches for the input value using animation like the Find function
  3. If the input value is found, deletes that value (perhaps with an animation of it flying out of the window), and shows an animation moving the cell values from right to left, one at a time, to fill in the gap from the deleted value.  The animation of moving the cell values to fill the gap should go at the same speed as the Find function does.
  4. If the input value is not found, a message is displayed saying the value was not found

**Comment by IlanaRadinsky** [comment]
Resolved [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/5f0104eeeed0e2df2e01305cf40494f1ecb5d487) and [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/023ed8fdd62b78f799fa15d38acd9b4c48f32368).
