### ISSUE TITLE
Separate functions with arguments from ones without and add a delete specific item function in Array.py

### ISSUE THREAD

**Issue by JMCanning78** [IlanaRadinsky/datastructures-applets#3]
In the `Array.py` (formerly `ArrayBasic.py`) module:

- Rename the "Delete" button in the GUI to "Delete Rightmost"
- Reorganize the text entry array and buttons that require an input value in the text entry array to be grouped together.  The "Delete Rightmost" button will be grouped separately to indicate it doesn't use the input value
- Add a new "Delete" button that:
  1.  Requires an input value
  2. Searches for the input value using animation like the Find function
  3. If the input value is found, deletes that value (perhaps with an animation of it flying out of the window), and shows an animation moving the cell values from right to left, one at a time, to fill in the gap from the deleted value.  The animation of moving the cell values to fill the gap should go at the same speed as the Find function does, and should use a different colored pointer to pointer to point at the next value to be moved.
  4. If the input value is not found, a message is displayed saying the value was not found

**Comment by IlanaRadinsky** [comment]
These should be resolved with commits [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/d9fc570cd53be2654da58910806494e7494e6d4d) and [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/2a77a484958a02038b29dd673e9914f60768efd7).
@JMCanning78 I didn't add in the arrows when moving the cell values from right to left yet. Can you take a look at it and let me know if you still think its necessary?

**Comment by JMCanning78** [comment]
That's much nicer.  The animation of moving the values helps, but it makes me think about making it clear to viewers that the array is fixed size and we are just copying values into and out of it.  For that I think we need to show something a little different.
First, let me propose a different layout of the elements you already have.  Here's a picture:
![array visualization concept](https://user-images.githubusercontent.com/26984827/53120573-fcde1700-3506-11e9-8695-4ae1ba084895.png)
I'd like to group the operations in a box and then divide that into operations that need an operand and those that don't.  Giving them a slightly different color background will help distiguish them to users.  I think the speed control, message area, and exit button can all be in the bottom row below the operations.  The animation area remains on top.
For communicating the idea that the array is a sequential set of allocated memory cells, I'd like to leave the black outlines of the cells in a fixed position in the animation area, and just move the colored squares with their labels.  The picture above shows the 7 being deleted from the array as it flies up out of the window.  The empty cell remains in the array and will get filled when the 8 slides over.  The value of 7 floating out would not have a black outline around it, since it is not an array cell. 
 This would also enable communicating the allocated size of the array - black outlines showing how many cells are being used, plus gray ones on the right side showing allocated but unused cells.  (That would also mean checking for array overflow when users try to insert more items than the array can hold).
I'd carry over this same idea to the Sorting visualization, so that the array remains fixed, while shuffle, bubble sort, insertion sort, etc. are moving values around and then updating what's stored in the array.
I don't want to make this too hard.  I know the team is doing this as volunteers, and some of what I'm suggesting might be too complicated to implement.  Let me know if that's the case.

**Comment by IlanaRadinsky** [comment]
Sure, that makes sense. The only thing that isn't clear to me is the black vs. grey cell outlines. You want allocated by unused cells to be outlined in grey, and used cells to be outlined in black? Wouldn't it be just as clear that the cells are allocated but unused if they had the regular black outline but no colored square inside it?

**Comment by IlanaRadinsky** [comment]
[Update button layout](https://github.com/IlanaRadinsky/datastructures-applets/commit/7c3f01b6680962df93948d8510aa0114844c09c6)

**Comment by JMCanning78** [comment]
Sorry for the delay in responding.  You're right.  We only need black outlines on the array cells.  The unfilled ones (well, filled with white anyway) are unused.
After looking at your changes, I had several more requests on changes to the appearance.  Instead of writing them up, I made a fork of the repository to make changes in the code that would show you what I mean.  I will send a pull request for those changes, and you can look them over to see if they make sense to incorporate.
There are still other, functional changes needed.  For example, now that the array has an allocated number of cells, users should get an error if they attempt to add more values than what are allocated.  I'll write those up in separate issues that the team can fix.

**Comment by JMCanning78** [comment]
Ilana merged the branch that had the appearance changes on March 7.  This can be closed.
