### ISSUE TITLE
Prevent non-numeric and large inputs to arrays

### ISSUE THREAD

**Issue by JMCanning78** [IlanaRadinsky/datastructures-applets#4]
In the `Array.py` and `Sorting.py` modules (formerly `BasicArray.py` and `Array.py`):

- Prevent users from entering non-integer values in the text entry area.  If the text entry area can be customized to only accept numeric digits and ignore other keystrokes (or possibly blink the background red for 0.2 sec if a non-numeric key stroke is attempted), that would be best.  If validation can only be done when a function tries to read the value of the text entry area, then add a message saying "The input value must be a non-negative integer", and clear the text from the text entry area.
- Prevent large values from being entered by checking that value is less than 100.  If users attempt to run a function with an invalid integer value, show a message saying "The input value must be an integer from 0 to 99.", and clear the text from the text entry area.

**Comment by IlanaRadinsky** [comment]
Commit to prevent non-numeric inputs [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/d6b4b6e63472fe7ff54f483d8294f5558a848eb0)

**Comment by IlanaRadinsky** [comment]
Commit to prevent large values from being entered [here](https://github.com/IlanaRadinsky/datastructures-applets/commit/f39497d5f3374c8e5a8c9a72b205680fe878e2b3)
